<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Eigdo.Worker-7e96143d-acfe-41fc-a49f-0e54b169caa4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eigdo.Application\Eigdo.Application.csproj" />
    <ProjectReference Include="..\Eigdo.Infrastructure\Eigdo.Infrastructure.csproj" />
    <ProjectReference Include="..\Eigdo.Domain\Eigdo.Domain.csproj" />
  </ItemGroup>
</Project>
