// <auto-generated />
using System;
using Eigdo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eigdo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EigdoDbContext))]
    partial class EigdoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.BillingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AzulCustomerId")
                        .HasColumnType("text")
                        .HasColumnName("azul_customer_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_customer_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_billing_accounts");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("i_x_billing_accounts_company_id");

                    b.ToTable("billing_accounts");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.CheckoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_utc");

                    b.Property<int>("Gateway")
                        .HasColumnType("integer")
                        .HasColumnName("gateway");

                    b.Property<string>("GatewaySessionId")
                        .HasColumnType("text")
                        .HasColumnName("gateway_session_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_checkout_sessions");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("i_x_checkout_sessions_plan_id");

                    b.HasIndex("PriceId")
                        .HasDatabaseName("i_x_checkout_sessions_price_id");

                    b.ToTable("checkout_sessions");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("Gateway")
                        .HasColumnType("integer")
                        .HasColumnName("gateway");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text")
                        .HasColumnName("gateway_response");

                    b.Property<string>("GatewayTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("gateway_transaction_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_payment_transactions");

                    b.HasIndex("BillingAccountId")
                        .HasDatabaseName("i_x_payment_transactions_billing_account_id");

                    b.ToTable("payment_transactions");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("IncludedDocumentsPerMonth")
                        .HasColumnType("integer")
                        .HasColumnName("included_documents_per_month");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxCompanies")
                        .HasColumnType("integer")
                        .HasColumnName("max_companies");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_plans");

                    b.ToTable("plans");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("StripeId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_prices");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("i_x_prices_plan_id");

                    b.ToTable("prices");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("CurrentPeriodEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end_utc");

                    b.Property<DateTime>("CurrentPeriodStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start_utc");

                    b.Property<int>("DocumentsEmittedThisPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("documents_emitted_this_period");

                    b.Property<DateTime?>("EndDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_utc");

                    b.Property<int>("Gateway")
                        .HasColumnType("integer")
                        .HasColumnName("gateway");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_id");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTime?>("TrialEndDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_end_date_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.HasIndex("BillingAccountId")
                        .HasDatabaseName("i_x_subscriptions_billing_account_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("i_x_subscriptions_plan_id");

                    b.HasIndex("PriceId")
                        .HasDatabaseName("i_x_subscriptions_price_id");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Emission.EcfDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<string>("AlanubePayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("alanube_payload_json");

                    b.Property<string>("AlanubeResponseJson")
                        .HasColumnType("text")
                        .HasColumnName("alanube_response_json");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("EcfType")
                        .HasColumnType("integer")
                        .HasColumnName("ecf_type");

                    b.Property<string>("Encf")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("encf");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("LastRetryUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_utc");

                    b.Property<Guid?>("OriginalEcfDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_ecf_document_id");

                    b.Property<string>("QboDocNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("qbo_doc_number");

                    b.Property<string>("QboSourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qbo_source_id");

                    b.Property<int>("QboSourceType")
                        .HasColumnType("integer")
                        .HasColumnName("qbo_source_type");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TrackId")
                        .HasColumnType("text")
                        .HasColumnName("track_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_ecf_documents");

                    b.HasIndex("Encf");

                    b.HasIndex("OriginalEcfDocumentId")
                        .HasDatabaseName("i_x_ecf_documents_original_ecf_document_id");

                    b.HasIndex("TrackId");

                    b.HasIndex("CompanyId", "Status");

                    b.ToTable("ecf_documents");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Emission.EcfEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DetailJson")
                        .HasColumnType("text")
                        .HasColumnName("detail_json");

                    b.Property<Guid>("EcfDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("ecf_document_id");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer")
                        .HasColumnName("from_status");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer")
                        .HasColumnName("to_status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_ecf_events");

                    b.HasIndex("EcfDocumentId")
                        .HasDatabaseName("i_x_ecf_events_ecf_document_id");

                    b.ToTable("ecf_events");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Emission.ProviderMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<Guid>("EcfDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("ecf_document_id");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("text")
                        .HasColumnName("http_method");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("RequestJson")
                        .HasColumnType("text")
                        .HasColumnName("request_json");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("text")
                        .HasColumnName("response_json");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("p_k_provider_messages");

                    b.HasIndex("EcfDocumentId")
                        .HasDatabaseName("i_x_provider_messages_ecf_document_id");

                    b.ToTable("provider_messages");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.CertificateStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("EncryptedCertificateData")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_certificate_data");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_password");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("IssuerName")
                        .HasColumnType("text")
                        .HasColumnName("issuer_name");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("SubjectName")
                        .HasColumnType("text")
                        .HasColumnName("subject_name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from_utc");

                    b.Property<DateTime?>("ValidToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to_utc");

                    b.HasKey("Id")
                        .HasName("p_k_certificate_stores");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("i_x_certificate_stores_company_id");

                    b.ToTable("certificate_stores");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.DgiiMunicipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("integer")
                        .HasColumnName("province_id");

                    b.HasKey("Id")
                        .HasName("p_k_dgii_municipalities");

                    b.HasIndex("ProvinceId")
                        .HasDatabaseName("i_x_dgii_municipalities_province_id");

                    b.ToTable("dgii_municipalities");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.DgiiProvince", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_dgii_provinces");

                    b.ToTable("dgii_provinces");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.DgiiUnitMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_dgii_unit_measures");

                    b.ToTable("dgii_unit_measures");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.FiscalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlanubeApiKey")
                        .HasColumnType("text")
                        .HasColumnName("alanube_api_key");

                    b.Property<string>("AlanubeEnvironment")
                        .HasColumnType("text")
                        .HasColumnName("alanube_environment");

                    b.Property<bool>("CertificateConfigured")
                        .HasColumnType("boolean")
                        .HasColumnName("certificate_configured");

                    b.Property<DateTime?>("CertificateExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("certificate_expires_utc");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("DefaultGoodServiceIndicator")
                        .HasColumnType("integer")
                        .HasColumnName("default_good_service_indicator");

                    b.Property<int?>("DefaultIncomeType")
                        .HasColumnType("integer")
                        .HasColumnName("default_income_type");

                    b.Property<int?>("DefaultNoTaxCodeBillingIndicator")
                        .HasColumnType("integer")
                        .HasColumnName("default_no_tax_code_billing_indicator");

                    b.Property<int?>("DefaultUnitMeasure")
                        .HasColumnType("integer")
                        .HasColumnName("default_unit_measure");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<int?>("MunicipioDgiiId")
                        .HasColumnType("integer")
                        .HasColumnName("municipio_dgii_id");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nombre_comercial");

                    b.Property<int?>("ProvinciaDgiiId")
                        .HasColumnType("integer")
                        .HasColumnName("provincia_dgii_id");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Rnc")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("rnc");

                    b.Property<int?>("TaxAmountIndicator")
                        .HasColumnType("integer")
                        .HasColumnName("tax_amount_indicator");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_fiscal_settings");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("i_x_fiscal_settings_company_id");

                    b.ToTable("fiscal_settings");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.PaymentConditionMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DgiiPaymentType")
                        .HasColumnType("integer")
                        .HasColumnName("dgii_payment_type");

                    b.Property<Guid>("FiscalSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_settings_id");

                    b.Property<string>("QboSalesTermId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qbo_sales_term_id");

                    b.Property<string>("QboSalesTermName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qbo_sales_term_name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_payment_condition_mappings");

                    b.HasIndex("FiscalSettingsId", "QboSalesTermId")
                        .IsUnique();

                    b.ToTable("payment_condition_mappings");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.PaymentMethodMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DgiiPaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("dgii_payment_method");

                    b.Property<Guid>("FiscalSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_settings_id");

                    b.Property<string>("QboPaymentMethodId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qbo_payment_method_id");

                    b.Property<string>("QboPaymentMethodName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qbo_payment_method_name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_payment_method_mappings");

                    b.HasIndex("FiscalSettingsId", "QboPaymentMethodId")
                        .IsUnique();

                    b.ToTable("payment_method_mappings");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.Sequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AlertThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("alert_threshold");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("CurrentValue")
                        .HasColumnType("bigint")
                        .HasColumnName("current_value");

                    b.Property<DateTime>("DueDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date_utc");

                    b.Property<int>("EcfType")
                        .HasColumnType("integer")
                        .HasColumnName("ecf_type");

                    b.Property<Guid>("FiscalSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_settings_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("RangeEnd")
                        .HasColumnType("bigint")
                        .HasColumnName("range_end");

                    b.Property<long>("RangeStart")
                        .HasColumnType("bigint")
                        .HasColumnName("range_start");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_sequences");

                    b.HasIndex("FiscalSettingsId", "EcfType", "IsActive");

                    b.ToTable("sequences");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_utc");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("text")
                        .HasColumnName("email_confirmation_token");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmation_token_expires_utc");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_utc");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expires_utc");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("SystemRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("system_role");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Integration.QboConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token_encrypted");

                    b.Property<DateTime>("AccessTokenExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_utc");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_utc");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("realm_id");

                    b.Property<string>("RefreshTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_encrypted");

                    b.Property<DateTime>("RefreshTokenExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_qbo_connections");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("i_x_qbo_connections_company_id");

                    b.ToTable("qbo_connections");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Integration.QboSyncEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_qbo_sync_events");

                    b.HasIndex("CompanyId", "Processed");

                    b.ToTable("qbo_sync_events");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Mapping.CustomerMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<int?>("MunicipioDgiiId")
                        .HasColumnType("integer")
                        .HasColumnName("municipio_dgii_id");

                    b.Property<int?>("ProvinciaDgiiId")
                        .HasColumnType("integer")
                        .HasColumnName("provincia_dgii_id");

                    b.Property<string>("QboCustomerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qbo_customer_id");

                    b.Property<string>("QboDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("qbo_display_name");

                    b.Property<string>("RazonSocialDgii")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("razon_social_dgii");

                    b.Property<string>("Rnc")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("rnc");

                    b.Property<int>("TipoComprobante")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_comprobante");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_customer_mappings");

                    b.HasIndex("CompanyId", "QboCustomerId")
                        .IsUnique();

                    b.ToTable("customer_mappings");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Mapping.ItemOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("GoodServiceIndicatorOverride")
                        .HasColumnType("integer")
                        .HasColumnName("good_service_indicator_override");

                    b.Property<string>("QboItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qbo_item_id");

                    b.Property<string>("QboItemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("qbo_item_name");

                    b.Property<string>("QboItemType")
                        .HasColumnType("text")
                        .HasColumnName("qbo_item_type");

                    b.Property<int?>("UnitMeasureOverride")
                        .HasColumnType("integer")
                        .HasColumnName("unit_measure_override");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_item_overrides");

                    b.HasIndex("CompanyId", "QboItemId")
                        .IsUnique();

                    b.ToTable("item_overrides");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Mapping.TaxCodeMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BillingIndicator")
                        .HasColumnType("integer")
                        .HasColumnName("billing_indicator");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("QboTaxCodeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qbo_tax_code_id");

                    b.Property<string>("QboTaxCodeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qbo_tax_code_name");

                    b.Property<decimal?>("QboTaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("qbo_tax_rate");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_tax_code_mappings");

                    b.HasIndex("CompanyId", "QboTaxCodeId")
                        .IsUnique();

                    b.ToTable("tax_code_mappings");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Mapping.VendorMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<int?>("MunicipioDgiiId")
                        .HasColumnType("integer")
                        .HasColumnName("municipio_dgii_id");

                    b.Property<int?>("ProvinciaDgiiId")
                        .HasColumnType("integer")
                        .HasColumnName("provincia_dgii_id");

                    b.Property<string>("QboDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("qbo_display_name");

                    b.Property<string>("QboVendorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qbo_vendor_id");

                    b.Property<string>("RazonSocialDgii")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("razon_social_dgii");

                    b.Property<decimal?>("RetentionIsrRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("retention_isr_rate");

                    b.Property<decimal?>("RetentionItbisRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("retention_itbis_rate");

                    b.Property<string>("Rnc")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("rnc");

                    b.Property<int>("TipoComprobante")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_comprobante");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_vendor_mappings");

                    b.HasIndex("CompanyId", "QboVendorId")
                        .IsUnique();

                    b.ToTable("vendor_mappings");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Support.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("new_values_json");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("old_values_json");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_audit_logs");

                    b.HasIndex("CompanyId", "CreatedAtUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Support.CertificationAssistanceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ChargeOnNextBillingCycle")
                        .HasColumnType("boolean")
                        .HasColumnName("charge_on_next_billing_cycle");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EstimatedDays")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_days");

                    b.Property<string>("IncludedItems")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("included_items");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_certification_assistance_configs");

                    b.ToTable("certification_assistance_configs");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Support.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_support_tickets");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("i_x_support_tickets_company_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_support_tickets_user_id");

                    b.ToTable("support_tickets");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Support.SupportTicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsStaffReply")
                        .HasColumnType("boolean")
                        .HasColumnName("is_staff_reply");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sender_email");

                    b.Property<string>("SenderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sender_name");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_support_ticket_messages");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("i_x_support_ticket_messages_ticket_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_support_ticket_messages_user_id");

                    b.ToTable("support_ticket_messages");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Tenancy.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOnboardingComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_onboarding_complete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("OnboardingStep")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_step");

                    b.Property<string>("Rnc")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("rnc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_companies");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Tenancy.CompanyUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_company_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_company_users_user_id");

                    b.HasIndex("CompanyId", "UserId")
                        .IsUnique();

                    b.ToTable("company_users");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.BillingAccount", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithOne("BillingAccount")
                        .HasForeignKey("Eigdo.Domain.Entities.Billing.BillingAccount", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_billing_accounts__companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.CheckoutSession", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Billing.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_checkout_sessions__plans_plan_id");

                    b.HasOne("Eigdo.Domain.Entities.Billing.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_checkout_sessions__prices_price_id");

                    b.Navigation("Plan");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.PaymentTransaction", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Billing.BillingAccount", "BillingAccount")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_payment_transactions_billing_accounts_billing_account_id");

                    b.Navigation("BillingAccount");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.Price", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Billing.Plan", "Plan")
                        .WithMany("Prices")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_prices_plans_plan_id");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.Subscription", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Billing.BillingAccount", "BillingAccount")
                        .WithMany("Subscriptions")
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_subscriptions_billing_accounts_billing_account_id");

                    b.HasOne("Eigdo.Domain.Entities.Billing.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_subscriptions_plans_plan_id");

                    b.HasOne("Eigdo.Domain.Entities.Billing.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_subscriptions_prices_price_id");

                    b.Navigation("BillingAccount");

                    b.Navigation("Plan");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Emission.EcfDocument", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_ecf_documents__companies_company_id");

                    b.HasOne("Eigdo.Domain.Entities.Emission.EcfDocument", "OriginalEcfDocument")
                        .WithMany()
                        .HasForeignKey("OriginalEcfDocumentId")
                        .HasConstraintName("f_k_ecf_documents_ecf_documents_original_ecf_document_id");

                    b.Navigation("Company");

                    b.Navigation("OriginalEcfDocument");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Emission.EcfEvent", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Emission.EcfDocument", "EcfDocument")
                        .WithMany("Events")
                        .HasForeignKey("EcfDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_ecf_events_ecf_documents_ecf_document_id");

                    b.Navigation("EcfDocument");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Emission.ProviderMessage", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Emission.EcfDocument", "EcfDocument")
                        .WithMany()
                        .HasForeignKey("EcfDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_provider_messages_ecf_documents_ecf_document_id");

                    b.Navigation("EcfDocument");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.CertificateStore", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_certificate_stores__companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.DgiiMunicipality", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Fiscal.DgiiProvince", "Province")
                        .WithMany("Municipalities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_dgii_municipalities__dgii_provinces_province_id");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.FiscalSettings", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithOne("FiscalSettings")
                        .HasForeignKey("Eigdo.Domain.Entities.Fiscal.FiscalSettings", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fiscal_settings__companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.PaymentConditionMapping", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Fiscal.FiscalSettings", "FiscalSettings")
                        .WithMany("PaymentConditionMappings")
                        .HasForeignKey("FiscalSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_payment_condition_mappings_fiscal_settings_fiscal_settings_~");

                    b.Navigation("FiscalSettings");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.PaymentMethodMapping", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Fiscal.FiscalSettings", "FiscalSettings")
                        .WithMany("PaymentMethodMappings")
                        .HasForeignKey("FiscalSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_payment_method_mappings_fiscal_settings_fiscal_settings_id");

                    b.Navigation("FiscalSettings");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.Sequence", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Fiscal.FiscalSettings", "FiscalSettings")
                        .WithMany("Sequences")
                        .HasForeignKey("FiscalSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_sequences_fiscal_settings_fiscal_settings_id");

                    b.Navigation("FiscalSettings");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_refresh_tokens__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Integration.QboConnection", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithOne("QboConnection")
                        .HasForeignKey("Eigdo.Domain.Entities.Integration.QboConnection", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_qbo_connections__companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Integration.QboSyncEvent", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_qbo_sync_events__companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Mapping.CustomerMapping", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_customer_mappings__companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Mapping.ItemOverride", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_item_overrides__companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Mapping.TaxCodeMapping", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_tax_code_mappings__companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Mapping.VendorMapping", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_vendor_mappings__companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Support.SupportTicket", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("f_k_support_tickets__companies_company_id");

                    b.HasOne("Eigdo.Domain.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("f_k_support_tickets_users_user_id");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Support.SupportTicketMessage", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Support.SupportTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_support_ticket_messages_support_tickets_ticket_id");

                    b.HasOne("Eigdo.Domain.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("f_k_support_ticket_messages_users_user_id");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Tenancy.CompanyUser", b =>
                {
                    b.HasOne("Eigdo.Domain.Entities.Tenancy.Company", "Company")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_company_users_companies_company_id");

                    b.HasOne("Eigdo.Domain.Entities.Identity.User", "User")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_company_users_users_user_id");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.BillingAccount", b =>
                {
                    b.Navigation("PaymentTransactions");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Billing.Plan", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Emission.EcfDocument", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.DgiiProvince", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Fiscal.FiscalSettings", b =>
                {
                    b.Navigation("PaymentConditionMappings");

                    b.Navigation("PaymentMethodMappings");

                    b.Navigation("Sequences");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("CompanyUsers");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Support.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Eigdo.Domain.Entities.Tenancy.Company", b =>
                {
                    b.Navigation("BillingAccount");

                    b.Navigation("CompanyUsers");

                    b.Navigation("FiscalSettings");

                    b.Navigation("QboConnection");
                });
#pragma warning restore 612, 618
        }
    }
}
